/*
	author = Reimchen
	description = Funktionen zum ausrüsten
*/

_selectedIndex = lbCurSel 5109;

if (_selectedIndex == 0) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		player addItem "BWA3_optic_NSA80";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Atschuetze_Bw_Flecktarn";
		player addWeapon "BWA3_G36_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		[player, "BWA3_Pzf3", 1] call BIS_fnc_addWeapon;
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Atschuetze_Us_Desert";
		player addWeapon "rhs_weap_m4a1_grip";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3_USMC";
		[player, "rhs_weap_M136", 1] call BIS_fnc_addWeapon;
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "ACE_Yardage450";
	};
};
if (_selectedIndex == 1) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;	
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Funkerfac_Bw_Flecktarn";
		player addItemToBackpack "Laserbatteries";
		player addWeapon "BWA3_G36_AG_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Laserdesignator";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Funkerfac_Us_Desert";
		player addItemToBackpack "Laserbatteries";
		player addWeapon "rhs_weap_m4a1_m320";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Laserdesignator";
	};
};
if (_selectedIndex == 2) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Gefechtssanitaeter_Bw_Flecktarn";
		player addWeapon "BWA3_G36_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
		player setVariable ["ace_medical_medicClass", 1];
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Gefechtssanitaeter_Us_Desert";
		player addWeapon "rhs_weap_m4a1_grip";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3_USMC";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Binocular";
		player setVariable ["ace_medical_medicClass", 1];
	};
};
if (_selectedIndex == 3) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Grenadier_Bw_Flecktarn";
		player addWeapon "BWA3_G36_AG_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Grenadier_Us_Desert";
		player addWeapon "rhs_weap_m4a1_m320";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Binocular";
	};
};
if (_selectedIndex == 4) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		player addBackpack "TTT_Backpack_Mgschuetze_Bw_Flecktarn";
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 4 do {player addItem "BWA3_200Rnd_556x45";};
		player addWeapon "BWA3_MG4_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "rhsusf_acc_eotech_552";
		player addItem "rhsusf_acc_ELCAN";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		player addItem "rhsusf_200Rnd_556x45_soft_pouch";
		player addBackpack "TTT_Backpack_Lmgschuetze_Us_Desert";
		player addWeapon "rhs_weap_m249_pip_L";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Binocular";
	};
};
if (_selectedIndex == 5) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Mgassistent_Bw_Flecktarn";
		player addWeapon "BWA3_G36_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "ACE_Yardage450";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Mgassistent_Us_Desert";
		player addWeapon "rhs_weap_m4a1_grip";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3_USMC";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "ACE_Yardage450";
	};
};
if (_selectedIndex == 6) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 3 do {player addItem "BWA3_120Rnd_762x51";};
		player addBackpack "TTT_Backpack_Mgschuetze_Bw_Flecktarn";
		player addWeapon "BWA3_MG5_Tan_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "rhsusf_acc_eotech_552";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		player addItem "rhsusf_100Rnd_762x51_m80a1epr";
		player addBackpack "TTT_Backpack_Mgschuetze_Us_Desert";
		player addWeapon "rhs_weap_m240b_elcan";
		player addPrimaryWeaponItem "rhsusf_acc_ELCAN";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Binocular";
	};
};
if (_selectedIndex == 7) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Pionier_Bw_Flecktarn";
		player addWeapon "BWA3_G36_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "Binocular";
		
		player setVariable ["ACE_isEOD", true];
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Pionier_Us_Desert";
		player addWeapon "rhs_weap_m4a1_grip";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3_USMC";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "Binocular";
		player setVariable ["ACE_isEOD", true];
	};
};
if (_selectedIndex == 8) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "ACE_Kestrel4500";
		player addItem "ACE_ATragMX";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		player addItem "ACE_RangeCard";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "7Rnd_408_Mag";};
		player addBackpack "TTT_Backpack_Schuetze_Bw_Flecktarn";
		player addWeapon "srifle_LRR_LRPS_F";
		player addPrimaryWeaponItem "optic_LRPS";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "ACE_Vector";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "ACE_Kestrel4500";
		player addItem "ACE_ATragMX";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		player addItem "ACE_RangeCard";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "7Rnd_408_Mag";};
		player addBackpack "TTT_Backpack_Schuetze_Us_Desert";
		player addWeapon "srifle_LRR_LRPS_F";
		player addPrimaryWeaponItem "optic_LRPS";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "ACE_Vector";
	};
};
if (_selectedIndex == 9) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "BWA3_muzzle_snds_G28";
		player addItem "ACE_NVG_Wide";
		player addItem "ACE_Kestrel4500";
		player addItem "ACE_ATragMX";
		for "_i" from 1 to 3 do {player addItem "ACE_CableTie";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		player addItem "ACE_RangeCard";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 4 do {player addItem "BWA3_20Rnd_762x51_G28_AP";};
		for "_i" from 1 to 2 do {player addItem "BWA3_20Rnd_762x51_G28_SD";};
		player addBackpack "TTT_Backpack_Truppfuehrer_Bw_Flecktarn";
		player addWeapon "BWA3_G27_AG_equipped";
		player addPrimaryWeaponItem "BWA3_acc_VarioRay_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_EOTech_Mag_Off";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "ACE_Vector";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "rhsusf_acc_eotech_552";
		player addItem "rhsusf_acc_rotex5_grey";
		player addItem "ACE_NVG_Wide";
		player addItem "ACE_Kestrel4500";
		player addItem "ACE_ATragMX";
		for "_i" from 1 to 3 do {player addItem "ACE_CableTie";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		player addItem "ACE_RangeCard";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Funkerfac_Us_Desert";
		player addWeapon "rhs_weap_m4a1_m320";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "ACE_Vector";
	};
};
if (_selectedIndex == 10) exitWith {
	if (reim_arsenal_bw) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "BWA3_optic_NSV600";
		player addItem "ACE_NVG_Wide";
		for "_i" from 1 to 3 do {player addItem "ACE_CableTie";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "11Rnd_45ACP_Mag";};
		for "_i" from 1 to 6 do {player addItem "BWA3_30Rnd_556x45_G36_AP";};
		player addBackpack "TTT_Backpack_Truppfuehrer_Bw_Flecktarn";
		player addWeapon "BWA3_G36_AG_equipped";
		player addPrimaryWeaponItem "BWA3_acc_LLM01_irlaser";
		player addPrimaryWeaponItem "BWA3_optic_ZO4x30";
		player addWeapon "hgun_Pistol_heavy_01_snds_F";
		player addHandgunItem "muzzle_snds_acp";
		player addWeapon "ACE_Yardage450";
	};
	if (reim_arsenal_rus) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
	if (reim_arsenal_us) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
		player addItem "ACE_NVG_Wide";
		player addItem "rhsusf_acc_eotech_552";
		for "_i" from 1 to 3 do {player addItem "ACE_CableTie";};
		player addItem "ACE_microDAGR";
		for "_i" from 1 to 2 do {player addItem "ACE_IR_Strobe_Item";};
		player addItem "ACE_MapTools";
		player addItem "ACE_Flashlight_XL50";
		for "_i" from 1 to 5 do {player addItem "SmokeShell";};
		for "_i" from 1 to 2 do {player addItem "SmokeShellPurple";};
		for "_i" from 1 to 2 do {player addItem "ACE_HandFlare_Green";};
		for "_i" from 1 to 2 do {player addItem "ACE_M84";};
		for "_i" from 1 to 2 do {player addItem "rhsusf_mag_7x45acp_MHP";};
		for "_i" from 1 to 6 do {player addItem "rhs_mag_30Rnd_556x45_Mk318_Stanag";};
		player addBackpack "TTT_Backpack_Truppfuehrer_Us_Desert";
		player addWeapon "rhs_weap_m4a1_m320";
		player addPrimaryWeaponItem "rhsusf_acc_anpeq15";
		player addPrimaryWeaponItem "rhsusf_acc_ACOG3";
		player addWeapon "rhsusf_weap_m1911a1";
		player addWeapon "ACE_Yardage450";
	};
};
/*
if (_selectedIndex == ---) exitWith {
	if (---) exitWith {
		closeDialog 0;
		reim_arsenal_us = false;
		reim_arsenal_bw = false;
		reim_arsenal_rus = false;
		removeAllWeapons player;
		{player removeMagazine _x} forEach magazines player;
		removeBackpack player;
	};
};
*/

hint "Markiere zuerst eine Seite/Fraktion/Klasse";
